# Generated by Django 5.0.3 on 2024-03-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
